import { Router } from 'express';
import express from 'express';
import { signupUserController,verifyOtpController,addUserDetailsController } from '../controllers/user.controller';
import { loginController } from '../controllers/auth.controller';
import { verifyToken } from '../validators/verifyToken';
const router = express.Router();
router.post('/signup-user1', signupUserController);
router.post('/verify-otp', verifyOtpController);
router.post('/login',loginController);
router.post('/add-user-detail',verifyToken,addUserDetailsController);
export default router;
